name: easy_ads_flutter
description: Easy Ads is a wrapper around famous ad packages which let you integrate ads easily
version: 2.3.3
homepage: https://github.com/nooralibutt/easy-ads
repository: https://github.com/nooralibutt/easy-ads

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.4.0
  collection: ^1.17.0
  unity_ads_plugin: ^0.3.8
  applovin_max: ^2.4.6
  easy_audience_network: ^0.0.6
  logger: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
